#공통설정

server:
  port: 4000

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@${db.host}:${db.port}:XE
    username: ${db.username}
    password: ${db.password}

  jpa:
    properties:
      hibernate:
        show_sql: true #sql 보이게
        format_sql: true #줄개행
        use_sql_comments: true #설명
    hibernate:
      ddl-auto: update
  #라이브 리로드 설정
  devtools:
    livereload:
      enabled: true

  #정작 자원 설정(css, js, 이미지) - 코드 바꼈을때 바로 반영되도록
  web:
    resources:
      static-locations: file:src/main/resources/static/

  # 파일 업로드 용량 설정
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 60MB # 전체 최대 용량
      file-size-threshold: 30MB # 메모리 초과 되면 임시 폴더에서 만들어짐

#파일 업로드 경로 설정
file:
  upload:
    path: D:/uploads
    url: /upload/ #정적경로


# 로거설정
logging:
  level:
    org.hibernate.type: trace # SQL 타입 변환과 관련된 상세 정보를 확인(가장 상세한 로그레벨)
    org.hibernate.orm.jdbc.bind: trace